#!/bin/bash
source /etc/captiveportal/config
intForwarded=0
if [[ "$localnet" == "" ]]
then
echo "$0: need localnet to have a ip network address and prefix in /etc/captiveportal/config file"
echo "Example: 192.168.128.0/24"
exit 1
fi
if [[ "$wan_interface" == "$lan_interface" ]]
then
iptables -t nat -A POSTROUTING -o $wan_interface -s $localnet -j MASQUERADE
#iptables -A FORWARD -i $lan_interface -s $localnet -j ACCEPT
iptables -A FORWARD -i $lan_interface -o $lan_interface -m state --state ESTABLISHED,RELATED -j ACCEPT
intForwarded=1
fi
if [[ "$intForwarded" == "0" ]]
then
#iptables -A FORWARD -i $lan_interface -o $wan_interface -j ACCEPT
iptables -A FORWARD -i $wan_interface -o $lan_interface -m state --state ESTABLISHED,RELATED -j ACCEPT
fi
iptables -A FORWARD -i $lan_interface -s $localnet -j DROP
iptables -P FORWARD DROP
current_value=$(sysctl -n net.ipv4.ip_forward)

# Check if the current value is not 1
if [ "$current_value" -ne 1 ]; then
  # Update /etc/sysctl.conf to ensure ip_forward is set to 1
  sysctl -w net.ipv4.ip_forward=1
  # Ensure it's persistent across reboots
  sed -i '/^net.ipv4.ip_forward=/c\net.ipv4.ip_forward=1' /etc/sysctl.conf
  # Reload sysctl settings
 sysctl -p
fi
if [[ "$1" != "service" ]]
then
apt install iptables-persistent
netfilter-persistent save
netfilter-persistent reload
fi
